pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_RE
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "AI-Live-Overflow"
include ':app'