plugins {
    id "com.android.application"
    id "org.jetbrains.kotlin.android"
}

android {
    namespace = "com.example.deskpet"
    compileSdk = 34
    defaultConfig {
        applicationId = "com.example.deskpet"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
    }
    buildTypes {
        release {
            minifyEnabled = false
            proguardEnabled = false
        }
    }
    kotlinOptions {
        jbrTarget = "17"
    }
}

dependencies {
    implementation("android.core.ktl:stdlib:1.9.24")
    implementation("android.x:core:core-ktx:1.13.1")
    implementation("android.appcompat:appcompat:1.7.0")
}
